### PR TITLE
Do not allow the guests and the bots to access to the flags list and …

### PR DESCRIPTION
**Pull request by Galixte**
…the user flag users

### CODE REVIEW

**Comment by Galixte** [comment]
Hi,

I prefer that you add the proper permissions for those pages, by example: “Can see the flag users page” & “Can see the flags list page”. Maybe the word “page” is in too.

In my opinion it’s privacy to know the provenence of users on the board. The bots collect informations about that.

**Comment by rmcgirr83** [comment]
Much ado about nothing.  Closing

**Comment by rmcgirr83** [comment]
https://github.com/RMcGirr83/phpBB-3.1-nationalflags/commit/57a675494d98f634d11bab5689132389b3239dbc

**Comment by Galixte** [comment]
:+1:

**Pull request closed without merging**
